# Generated by Django 4.2.2 on 2023-07-06 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2023, 7, 6), verbose_name='Примьеры в мире'),
        ),
    ]
